version: '3.8'

networks:
  banking-network-kafka:
    driver: bridge

volumes:
  kafka-data:
  schema-data:
  pgdata:

services:
  # -----------------------------
  # Kafka Broker (KRaft mode)
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-banking
    hostname: kafka
    ports:
      - "9092:9092"   # external (for Spring Boot / localhost)
      - "29092:29092" # internal (for Docker services)
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1

      # Listeners: external, internal, controller
      KAFKA_LISTENERS: PLAINTEXT_EXTERNAL://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # KRaft quorum (single-node)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Replication / transaction
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Cluster ID (pre-generated UUID)
      CLUSTER_ID: 383d9e96-76e1-4441-bc4a-2102308d5e31

    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - banking-network-kafka

  # -----------------------------
  # Schema Registry
  # -----------------------------
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry-banking
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: BACKWARD
    volumes:
      - schema-data:/var/lib/schema-registry/data
    networks:
      - banking-network-kafka

  # -----------------------------
  # Kafka Connect
  # -----------------------------
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect-banking
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect_configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: _connect_offset
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: _connect_status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect0
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    networks:
      - banking-network-kafka

  # -----------------------------
  # Postgres for Kafka UI
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: kafkaui-postgres
    environment:
      POSTGRES_USER: kafkaui
      POSTGRES_PASSWORD: kafkaui
      POSTGRES_DB: kafkaui
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banking-network-kafka

  # -----------------------------
  # Kafka UI (kafbat-ui)
  # -----------------------------
  kafkabat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafkabat-ui
    depends_on:
      - postgres
      - kafka
      - schema-registry
      - kafka-connect
    ports:
      - "9090:8080"   # Avoid clash with Keycloak
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8082
      DYNAMIC_CONFIG_ENABLED: 'true'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kafkaui
      SPRING_DATASOURCE_USERNAME: kafkaui
      SPRING_DATASOURCE_PASSWORD: kafkaui
    networks:
      - banking-network-kafka
