spring:
  application:
    topic: user-create-event
    name: arya-banking-user-service
    database: user-service
    mongo-password: ${MONGO.PASSWORD}

  config:
    import: configserver:http://localhost:8090

  config:
    import: configserver:http://localhost:8090

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
        registration:
          user-service-client:
            provider: keycloak
            client-id: user-service-client
            client-secret: ${USER.SERVICE.CLIENT.SECRET}
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.jwk-set-uri}

app:
  metadata:
    versioning:
      enabled: true
  security:
    client-registrationId: user-service-client

server:
  port: 8086