name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and Test
        run: mvn --settings settings.xml clean verify -DskipTests
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build Docker Image
        run: mvn --settings settings.xml spring-boot:build-image -DskipTests
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
